server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/customers/**
            
        - id: ACCOUNT-SERVICE
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/accounts/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

